[package]
name = "shmemq"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
serde = { package = "serde", version = "1.0", features = [ "derive" ], optional = true }

[features]
default = [ ]
serde = [ "dep:serde" ]
